### ISSUE TITLE
[Request] Add the ability to change default speaker without modifying the communication ones

### ISSUE THREAD

**Issue by greggameplayer** [Far-Se/win32audio#1]
It would be great, if there will be the ability to change default speaker without modifying the communication ones because currently it removes the previous communication speaker chosen.

**Comment by Far-Se** [comment]
I do not understand, what communication ones? There are output(playback) devices and input(recording) devices. When you switch output the microphone cuts?

**Comment by greggameplayer** [comment]
on windows like you can see on my screenshot : 
![image](https://user-images.githubusercontent.com/33609333/186009039-3989c3f8-1492-4121-b10f-98fda2c0b7d3.png)

there are two types of playback devices to select, the default one (multimedia) and the communication one (which is optional but really useful when you want to fine tune sound with the arctis 5 headset for example with the knob )

**Comment by Far-Se** [comment]
Oh, I see, thanks for reporting, I've found the issue as well:
![image](https://user-images.githubusercontent.com/20853986/186070854-ad3343d9-5b4c-4be6-be30-bbf8289102ff.png)

I will update the function to specify what type you want to change, i will update it today.

Thanks for reporting!
