### ISSUE TITLE
[Feature Request] Add the possibility to get the default device in function of it's type and more

### ISSUE THREAD

**Issue by greggameplayer** [Far-Se/win32audio#2]
Hello, it would be good to be able to get the default device in function of it's type (console, multimedia, communication) and be able to get the volume from it

**Comment by Far-Se** [comment]
I've added `audioRole` parameter on functions that had `eMultimedia` as default
```dart
enum AudioRole {
  console,
  multimedia,
  communications,
}
```
I've also published to pub.dev

**Comment by greggameplayer** [comment]
thanks 🙂
